name: CommandCharges
main: me.chr1s0143.CommandCharges.Main
version: 1.0 Beta
author: Chris Hall
description: Commands cost a player $50
depend: ['Vault']
commands:
  commandcharges:
    usage: /commandcharges reload
    description: reload the config file
    aliases: [cc]